services:
  app:
    build: .
    container_name: chatbot_app
    ports:
      - "8501:8501" 
    volumes:
      - .:/app
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL} 
      - QDRANT_URL=${QDRANT_URL}
      - QDRANT_API_KEY=${QDRANT_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: always
    depends_on:
      - qdrant 

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_db
    ports:
      - "6333:6333"
    environment:
      - QDRANT_API_KEY=${QDRANT_API_KEY}
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  qdrant_data:
    driver: local
